import AppKit

/// NSPasteboard changeCount를 0.5초 주기로 폴링해서 새 복사 내용을 저장소에 넣는다.
@MainActor
final class ClipboardWatcher {
    private struct CapturedContent: Sendable {
        let kind: ClipboardItem.Kind
        let text: String?
        let imageData: Data?
        let imageIsPNG: Bool
        let capturedAt: Date
    }

    private var changeCount = NSPasteboard.general.changeCount
    private var isRunning = false
    var onChange: (() -> Void)?

    // 변경은 감지됐지만 아직 내용을 못 읽은(=앱이 쓰는 중인) changeCount와 재시도 횟수.
    // 이게 없으면 clearContents()~데이터쓰기 사이에 폴링이 걸렸을 때 그 복사를 영영 놓친다.
    private var pendingChangeCount = 0
    private var pendingRetries = 0
    private static let maxRetries = 6  // 0.5s * 6 = 3초 안에 못 읽으면 미지원 타입으로 판단

    /// 비밀번호 매니저 등이 표시하는 "기록 금지" 타입 (http://nspasteboard.org 규약)
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    func start() {
        guard !isRunning else { return }
        changeCount = NSPasteboard.general.changeCount
        isRunning = true
    }

    func stop() {
        isRunning = false
        resetPending()
    }

    /// AppDelegate의 0.5초 시스템 샘플 타이머와 같은 틱을 공유한다. 별도 타이머를
    /// 만들지 않아 동일 주기의 불필요한 런루프 깨우기를 하나 줄인다.
    func poll() {
        guard isRunning else { return }
        check()
    }

    private func check() {
        let pb = NSPasteboard.general
        let current = pb.changeCount
        guard current != changeCount else { return }

        let types = (pb.types ?? []).map(\.rawValue)

        // 비밀번호 매니저 등 "기록 금지" 타입: 변경으로 인정하고 넘어감(재시도 안 함).
        if types.contains(where: { Self.ignoredTypes.contains($0) }) {
            changeCount = current
            resetPending()
            return
        }

        if let content = capture(from: pb) {
            // 내용을 읽는 데 성공했을 때에만 changeCount를 확정한다.
            changeCount = current
            resetPending()
            persist(content)
            return
        }

        // 변경은 감지됐지만 아직 내용을 못 읽음 → 앱이 clearContents 후 데이터를 쓰는 중일 수
        // 있으므로 changeCount를 확정하지 않고 다음 폴링에서 재시도한다.
        if pendingChangeCount == current {
            pendingRetries += 1
            if pendingRetries >= Self.maxRetries {
                // 우리가 다루지 않는 타입(커스텀 등)으로 판단 — 무한 재시도를 막고 넘어간다.
                changeCount = current
                resetPending()
            }
        } else {
            pendingChangeCount = current
            pendingRetries = 1
        }
    }

    /// 읽을 내용을 가볍게 복사해 온다. 이미지 변환·해시·DB 쓰기는 actor 저장소에서 한다.
    private func capture(from pb: NSPasteboard) -> CapturedContent? {
        let capturedAt = Date()
        // 우선순위: 파일 > 텍스트 > 이미지
        if let urls = pb.readObjects(forClasses: [NSURL.self]) as? [URL],
            !urls.isEmpty, urls.allSatisfy(\.isFileURL)
        {
            let paths = urls.map(\.path).joined(separator: "\n")
            return CapturedContent(
                kind: .file, text: paths, imageData: nil, imageIsPNG: true,
                capturedAt: capturedAt)
        }
        if let string = pb.string(forType: .string),
            !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        {
            return CapturedContent(
                kind: .text, text: string, imageData: nil, imageIsPNG: true,
                capturedAt: capturedAt)
        }
        if let png = pb.data(forType: .png), !png.isEmpty {
            return CapturedContent(
                kind: .image, text: nil, imageData: png, imageIsPNG: true,
                capturedAt: capturedAt)
        }
        if let tiff = pb.data(forType: .tiff), !tiff.isEmpty {
            return CapturedContent(
                kind: .image, text: nil, imageData: tiff, imageIsPNG: false,
                capturedAt: capturedAt)
        }
        return nil
    }

    private func resetPending() {
        pendingChangeCount = 0
        pendingRetries = 0
    }

    private func persist(_ content: CapturedContent) {
        Task { [weak self] in
            let stored = await ClipboardStore.shared.add(
                kind: content.kind,
                text: content.text,
                imageData: content.imageData,
                imageIsPNG: content.imageIsPNG,
                createdAt: content.capturedAt)
            if stored { self?.onChange?() }
        }
    }

    /// 히스토리 항목을 클립보드에 다시 올린다.
    static func copyToPasteboard(_ item: ClipboardItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .text:
            pb.setString(item.text ?? "", forType: .string)
        case .file:
            let urls = (item.text ?? "").split(separator: "\n")
                .map { URL(fileURLWithPath: String($0)) as NSURL }
            pb.writeObjects(urls)
        case .image:
            if let data = item.imageData { pb.setData(data, forType: .png) }
        }
    }
}
