import AppKit

/// NSPasteboard changeCount를 0.5초 주기로 폴링해서 새 복사 내용을 저장소에 넣는다.
@MainActor
final class ClipboardWatcher {
    private var changeCount = NSPasteboard.general.changeCount
    private var timer: Timer?
    var onChange: (() -> Void)?

    /// 비밀번호 매니저 등이 표시하는 "기록 금지" 타입 (http://nspasteboard.org 규약)
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// 이미지 저장 상한 (초대형 이미지로 DB가 비대해지는 것 방지)
    private static let maxImageBytes = 10 * 1024 * 1024

    func start() {
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.check() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func check() {
        let pb = NSPasteboard.general
        guard pb.changeCount != changeCount else { return }
        changeCount = pb.changeCount

        let types = (pb.types ?? []).map(\.rawValue)
        guard !types.contains(where: { Self.ignoredTypes.contains($0) }) else { return }

        // 우선순위: 파일 > 텍스트 > 이미지
        if let urls = pb.readObjects(forClasses: [NSURL.self]) as? [URL],
            !urls.isEmpty, urls.allSatisfy(\.isFileURL)
        {
            let paths = urls.map(\.path).joined(separator: "\n")
            ClipboardStore.shared.add(kind: .file, text: paths, imageData: nil)
        } else if let string = pb.string(forType: .string),
            !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        {
            ClipboardStore.shared.add(kind: .text, text: string, imageData: nil)
        } else if let imageData = readImagePNG(from: pb) {
            guard imageData.count <= Self.maxImageBytes else { return }
            ClipboardStore.shared.add(kind: .image, text: nil, imageData: imageData)
        } else {
            return
        }
        onChange?()
    }

    private func readImagePNG(from pb: NSPasteboard) -> Data? {
        if let png = pb.data(forType: .png) { return png }
        guard let tiff = pb.data(forType: .tiff),
            let rep = NSBitmapImageRep(data: tiff)
        else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    /// 히스토리 항목을 클립보드에 다시 올린다.
    static func copyToPasteboard(_ item: ClipboardItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .text:
            pb.setString(item.text ?? "", forType: .string)
        case .file:
            let urls = (item.text ?? "").split(separator: "\n")
                .map { URL(fileURLWithPath: String($0)) as NSURL }
            pb.writeObjects(urls)
        case .image:
            if let data = item.imageData { pb.setData(data, forType: .png) }
        }
    }
}
